# Fundamentals of AIML - Notes

## Python Basics

1. LaTex equations
2. Key board shotcuts for Jupyter notebook
    * shift + enter (Run the cell and go to the next cell)
    * cmd + enter (Run the cell and stay on the same cell)
    * alt + enter (Run the existing cell and create a new cell below)
    * tab (Dropdown with suggestions)
    * shift + tab (Python function description for that function)
    
## Numpy
1. Math operations
2. Sine, Cosine,.. 
3. Random variable generation
4. Array generation

In [3]:
# Vector - One dimensional Array
# Matrix - Two dimentional Array
# Tensor - More than two dimentional Array

import numpy as np

In [5]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


In [6]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(mat.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# arange
We can create numpy arrays using 'arange' - array range

Same syntax as range command

arange(0,15) - 0 inclusive, 15 not included
arange(starting - inclusive, ending - exclusive, step size)

In [8]:
vec2=np.arange(0,15)
print(vec2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
vec3=np.arange(3,21,6)
print(vec3)

[ 3  9 15]


# linspace

linspace(0,5,10) - starting point and ending point are inclusive

linspace(starting - inclusive, ending - inclusive, how many points in the array)

In [16]:
vec4 = np.linspace(0,5,12);
print(vec4)

[0.         0.45454545 0.90909091 1.36363636 1.81818182 2.27272727
 2.72727273 3.18181818 3.63636364 4.09090909 4.54545455 5.        ]


In [18]:
vec5 = vec4.reshape(4,3)
print(vec5)
print(vec4)

[[0.         0.45454545 0.90909091]
 [1.36363636 1.81818182 2.27272727]
 [2.72727273 3.18181818 3.63636364]
 [4.09090909 4.54545455 5.        ]]
[0.         0.45454545 0.90909091 1.36363636 1.81818182 2.27272727
 2.72727273 3.18181818 3.63636364 4.09090909 4.54545455 5.        ]


vec4 will not be reshaped.

In [23]:
# Create array of zeros
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,1))
print(mat3)
# Identity matrix
mat4 = np.eye(3)
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]
 [1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Working with Arrays - Vector

In [27]:
# We can +-/* arrays together if they're the right size
vec6 = np.arange(1,5)
vec7 = np.arange(7,11)
print(vec6+vec7)
print(vec6-vec7)
print(vec6/vec7)
print(vec6*vec7)
print(np.sqrt(vec6))

[ 8 10 12 14]
[-6 -6 -6 -6]
[0.14285714 0.25       0.33333333 0.4       ]
[ 7 16 27 40]
[1.         1.41421356 1.73205081 2.        ]


In [28]:
# Randoms
randNum = np.random.rand(5,3) -> Uniform random variable. None of them are greater than one or lesser than 0
print(randNum)

[[0.91330347 0.61482899 0.12611336]
 [0.31848869 0.97671669 0.43935775]
 [0.08190698 0.28985833 0.51492953]
 [0.62322413 0.25913462 0.67552039]
 [0.95123271 0.07331332 0.6199837 ]]


In [33]:
randNumn = np.random.randn(2,3)
print(randNumn)
print(np.mean(randNumn))
print(np.std(randNumn))
print(np.mean(randNum))
print(np.std(randNum))

[[-0.15786811  0.80537356 -0.25167375]
 [ 0.76599336  0.01308589 -0.15307101]]
0.17030665572022874
0.4421934406755447
0.4985275106483741
0.2956244537164232


# Summary - Numpy 1
* import numpy as np
* np.array([1,2,3]) -> Converts python's list to array
* np.array([[1,2],[3,4],[5,6]]) -> Gives a matrix (list of lists)
* np.cos(np.pi)
* np.sqrt(1.21)
* np.log(np.exp(5.2))-> log base e
* np.arange(0,15)
* np.linspace(0,15,10)
* np.zeros([3,5]) -> matrix with zeros - 3 rows and 5 columns
* np.ones([4,5])
* np.eye(5) - Identity matrix - row = column
* reshape([3,4]) -> reshapes an array to the given row, column
* np.random.rand(5,3) -> uniform random variable
* np.mean(matrix)
* np.std(matrix)

In [38]:
vec1 = np.random.randn(20)
print(vec1)
print(vec1[5])

[-2.07458029 -1.85801267  0.28766641 -0.23970014 -0.29432201 -0.20238872
  2.57723232 -1.10921928 -0.36111087  0.59325893  0.21735789 -0.28542138
  0.20578589 -0.26622645  1.20719358 -0.01623848 -1.17556591 -0.13945271
 -1.26057478 -0.8863745 ]
-0.20238871536000094


In [37]:
print(vec1[2:4])

[0.83487837 0.35211533]


In [40]:
print(vec1[np.arange(0,15,5)])

[-2.07458029 -0.20238872  0.21735789]
